name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile and Deploy LaTeX to PDF
      uses: SoPra-Team-17/latex-action@master
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.3.0
      env:
        BUILD_DIR: "build/"
        GH_PAT: ${{ secrets.GH_PAT }}
